name: Package and release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      # Add the API Tokens below if you want automatic deployment to Curseforge, Wago or WowInterface
      # CF_API_KEY: ${{ secrets.CF_API_KEY }}
      # WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    steps:
      - name: Clone project
        # note: checkout@v2 breaks git history, so generating a changelog and
        # file naming for non-tagged builds will not work properly
        uses: actions/checkout@v2

      # Retail
      - name: Release for Retail
        uses: BigWigsMods/packager@v2

      # Classic
      - name: Release for Classic
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic

      # TBC Classic
      - name: Release for TBC Classic
        uses: BigWigsMods/packager@v2
        with:
          args:
            -g bcc

      # Wrath Classic
      - name: Release for Wrath Classic
        uses: BigWigsMods/packager@v2
        with:
          args: -g wrath
